apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.service.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - image: {{ .Values.image.repository }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }} 
        name: techtrends
        ports:
        - containerPort: {{ .Values.containers.containerPort }} 
          protocol: TCP
        livenessProbe:
          httpGet:
            path: {{ .Values.containers.livenessProbe.path }} 
            port: {{ .Values.containers.containerPort }} 
        readinessProbe:
          httpGet:
            path: {{ .Values.containers.readinessProbe.path }} 
            port: {{ .Values.containers.containerPort }} 
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }} 
            memory: {{ .Values.resources.requests.memory }} 
          limits:
            cpu: {{ .Values.resources.limits.cpu }} 
            memory: {{ .Values.resources.limits.memory }} 
