namespace:
  name: sandbox
 
image:
  repository: sale/techtrends 
  tag: latest
  imagePullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

service:
  port: 4111
  targetPort: 4111
  protocol: TCP
  type: ClusterIP

containers:
  containerPort: 3111
  livenessProbe:
    path: /healthz
  readinessProbe:
    path: /healthz
